# Generated by Django 4.0.2 on 2025-02-28 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_user_order_alter_movie_actors_alter_movie_genres_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='oder',
            new_name='order',
        ),
    ]
