# Generated by Django 5.1.4 on 2025-01-15 15:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0002_alter_movie_actors_alter_movie_genres_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
