# Generated by Django 4.0.2 on 2024-11-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "db",
            "0002_user_order_alter_movie_actors_alter_movie_genres_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("movie_session", "row", "seat"), name="unique_ticket"
            ),
        ),
    ]
