# Generated by Django 4.0.2 on 2025-03-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_order_options_ticket_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ticket',
            name='unique_ticket_per_session',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='row',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('movie_session', 'row', 'seat'), name='unique_ticket_per_session'),
        ),
    ]
