# Generated by Django 4.0.2 on 2024-11-15 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_user_order_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['created_at']},
        ),
    ]
