# Generated by Django 4.0.2 on 2025-02-13 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_user_options_user_unique_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_user_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
