# Generated by Django 4.0.2 on 2025-01-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_user'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title'], name='db_movie_title_5d0841_idx'),
        ),
    ]
