# Generated by Django 4.0.2 on 2025-01-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_ticket_seat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='row',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.PositiveIntegerField(),
        ),
    ]
