# Generated by Django 4.0.2 on 2024-12-08 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
