# Generated by Django 4.0.2 on 2024-11-15 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
