# Generated by Django 4.0.2 on 2025-01-30 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
    ]
